extends:
  - airbnb-base
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions:
        - .ts
  import/parsers:
    '@typescript-eslint/parser': [.ts]
rules:
  no-undef: off
  space-infix-ops: off
  import/extensions: [error, ignorePackages, {
    js: never,
  }]
  import/named: off
  import/prefer-default-export: off
  '@typescript-eslint/indent': [error, 2]
  '@typescript-eslint/no-explicit-any': off
overrides:
  - files: '**/*.test.ts'
    rules:
      import/no-extraneous-dependencies: off
